blank_issues_enabled: false

contact_links:
  - name: Report a bug
    url: https://github.com/your/repo/issues/new?template=bug_report.md
    about: Use this template to report problems.

  - name: Ask a question
    url: https://github.com/your/repo/issues/new?template=feature_request.md
    about: Use this template to request new features.
